[phases.setup]
nixPkgs = ["nodejs", "nodejs.npm", "coreutils"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048"
VITE_APP_ENV = "production"

[phases.setup.cache]
directories = [".npm"]

[start.healthcheck]
interval = "30s"
timeout = "5s"
retries = 3