[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048"
VITE_APP_ENV = "production"

[phases.setup.cache]
directories = [".npm"]

[start.healthcheck]
interval = "30s"
timeout = "5s"
retries = 3